/**
 * @file PrivacySecuritySettings.tsx
 * @description Controls for 2FA, session timeouts, telemetry opt-in, crash reporting, and session management.
 * @module Features/Settings/Components/Sections/PrivacySecuritySettings
 */

import React, { useState } from 'react';
import { Shield, Lock, Smartphone, EyeOff, Laptop, LogOut, CheckCircle2, Clock } from 'lucide-react';
import { useSettings } from '../../hooks/useSettings';
import { Button } from '@/components/ui/button';
import { SessionTimeoutOption } from '../../types';

export const PrivacySecuritySettings: React.FC = () => {
  const { privacy, updatePrivacy, revokeSession, playToggleSound } = useSettings();
  const [show2FAInfo, setShow2FAInfo] = useState(false);

  const handle2FAToggle = () => {
    playToggleSound();
    updatePrivacy({ twoFactorEnabled: !privacy.twoFactorEnabled });
  };

  return (
    <div className="space-y-8">
      {/* 1. Authentication & 2FA */}
      <div className="space-y-4">
        <div>
          <h3 className="text-base font-semibold text-[var(--color-text-primary)] flex items-center gap-2">
            <Shield className="w-4 h-4 text-[var(--color-accent)]" />
            <span>Multi-Factor Authentication (2FA)</span>
          </h3>
          <p className="text-xs text-[var(--color-text-secondary)]">
            Enforce secondary security verification via authenticator app or hardware keys.
          </p>
        </div>

        <div className="p-5 rounded-xl bg-[var(--color-surface)] border border-[var(--color-border)] flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-start gap-3">
            <div
              className={`p-2.5 rounded-xl border shrink-0 ${
                privacy.twoFactorEnabled
                  ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400'
                  : 'bg-[var(--color-surface-elevated)] border-[var(--color-border)] text-[var(--color-text-muted)]'
              }`}
            >
              <Smartphone className="w-5 h-5" />
            </div>
            <div className="space-y-1">
              <div className="text-xs font-semibold text-[var(--color-text-primary)] flex items-center gap-2">
                <span>Two-Factor Enforcement</span>
                <span
                  className={`text-[10px] font-mono px-2 py-0.5 rounded-full ${
                    privacy.twoFactorEnabled
                      ? 'bg-emerald-500/20 text-emerald-400'
                      : 'bg-amber-500/20 text-amber-400'
                  }`}
                >
                  {privacy.twoFactorEnabled ? 'PROTECTED' : 'DISABLED'}
                </span>
              </div>
              <p className="text-[11px] text-[var(--color-text-secondary)] leading-relaxed">
                Requires a 6-digit TOTP code generated by Google Authenticator, Authy, or 1Password.
              </p>
            </div>
          </div>

          <Button
            type="button"
            variant={privacy.twoFactorEnabled ? 'outline' : 'primary'}
            size="sm"
            onClick={handle2FAToggle}
            className="shrink-0"
          >
            {privacy.twoFactorEnabled ? 'Disable 2FA' : 'Enable 2FA Protection'}
          </Button>
        </div>
      </div>

      {/* 2. Session Inactivity Timeout */}
      <div className="space-y-4 pt-6 border-t border-[var(--color-border)]">
        <div>
          <h3 className="text-base font-semibold text-[var(--color-text-primary)] flex items-center gap-2">
            <Clock className="w-4 h-4 text-[var(--color-accent)]" />
            <span>Session Inactivity Lockout</span>
          </h3>
          <p className="text-xs text-[var(--color-text-secondary)]">
            Automatically lock or invalidate workspace sessions after idle duration.
          </p>
        </div>

        <div className="p-4 rounded-xl bg-[var(--color-surface)] border border-[var(--color-border)] space-y-2">
          <label className="text-xs font-medium text-[var(--color-text-primary)]">
            Idle Timeout Duration
          </label>
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-2 p-1 rounded-lg bg-[var(--color-surface-elevated)] border border-[var(--color-border)] text-xs font-mono">
            {(['15m', '30m', '1h', '4h', '8h', 'never'] as SessionTimeoutOption[]).map((opt) => (
              <button
                key={opt}
                type="button"
                onClick={() => {
                  playToggleSound();
                  updatePrivacy({ sessionTimeout: opt });
                }}
                className={`py-1.5 rounded-md uppercase transition-colors cursor-pointer ${
                  privacy.sessionTimeout === opt
                    ? 'bg-[var(--color-accent)] text-[var(--color-accent-foreground)] font-semibold'
                    : 'text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)]'
                }`}
              >
                {opt}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* 3. Telemetry & Privacy Toggles */}
      <div className="space-y-4 pt-6 border-t border-[var(--color-border)]">
        <div>
          <h3 className="text-base font-semibold text-[var(--color-text-primary)] flex items-center gap-2">
            <EyeOff className="w-4 h-4 text-[var(--color-accent)]" />
            <span>Privacy & Telemetry Opt-Ins</span>
          </h3>
          <p className="text-xs text-[var(--color-text-secondary)]">
            Control anonymous analytics, crash diagnostics, and strict data masking.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 rounded-xl bg-[var(--color-surface)] border border-[var(--color-border)] flex items-center justify-between">
            <div className="space-y-0.5">
              <div className="text-xs font-medium text-[var(--color-text-primary)]">
                Anonymous Usage Telemetry
              </div>
              <p className="text-[11px] text-[var(--color-text-secondary)]">
                Help improve Aura Core with performance metrics.
              </p>
            </div>
            <button
              type="button"
              onClick={() => {
                playToggleSound();
                updatePrivacy({ telemetryOptIn: !privacy.telemetryOptIn });
              }}
              className={`w-9 h-5 rounded-full transition-colors relative cursor-pointer ${
                privacy.telemetryOptIn ? 'bg-[var(--color-accent)]' : 'bg-gray-700'
              }`}
            >
              <span
                className={`absolute top-0.5 left-0.5 w-4 h-4 rounded-full bg-white transition-transform ${
                  privacy.telemetryOptIn ? 'translate-x-4' : 'translate-x-0'
                }`}
              />
            </button>
          </div>

          <div className="p-4 rounded-xl bg-[var(--color-surface)] border border-[var(--color-border)] flex items-center justify-between">
            <div className="space-y-0.5">
              <div className="text-xs font-medium text-[var(--color-text-primary)]">
                Crash & Error Diagnostics
              </div>
              <p className="text-[11px] text-[var(--color-text-secondary)]">
                Send anonymized stack traces on exceptions.
              </p>
            </div>
            <button
              type="button"
              onClick={() => {
                playToggleSound();
                updatePrivacy({ crashReportingOptIn: !privacy.crashReportingOptIn });
              }}
              className={`w-9 h-5 rounded-full transition-colors relative cursor-pointer ${
                privacy.crashReportingOptIn ? 'bg-[var(--color-accent)]' : 'bg-gray-700'
              }`}
            >
              <span
                className={`absolute top-0.5 left-0.5 w-4 h-4 rounded-full bg-white transition-transform ${
                  privacy.crashReportingOptIn ? 'translate-x-4' : 'translate-x-0'
                }`}
              />
            </button>
          </div>
        </div>
      </div>

      {/* 4. Active Sessions List */}
      <div className="space-y-4 pt-6 border-t border-[var(--color-border)]">
        <div>
          <h3 className="text-base font-semibold text-[var(--color-text-primary)] flex items-center gap-2">
            <Laptop className="w-4 h-4 text-[var(--color-accent)]" />
            <span>Active Session Management</span>
          </h3>
          <p className="text-xs text-[var(--color-text-secondary)]">
            Inspect active client devices authenticated with your user credentials.
          </p>
        </div>

        <div className="space-y-3">
          {privacy.activeSessions.map((session) => (
            <div
              key={session.id}
              className="p-4 rounded-xl bg-[var(--color-surface)] border border-[var(--color-border)] flex flex-col sm:flex-row sm:items-center justify-between gap-3"
            >
              <div className="flex items-start gap-3">
                <div className="p-2 rounded-lg bg-[var(--color-surface-elevated)] border border-[var(--color-border)] text-[var(--color-accent)] shrink-0 mt-0.5">
                  <Laptop className="w-4 h-4" />
                </div>
                <div className="space-y-1">
                  <div className="text-xs font-semibold text-[var(--color-text-primary)] flex items-center gap-2">
                    <span>{session.device}</span>
                    {session.isCurrent && (
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-400 font-semibold">
                        This Device
                      </span>
                    )}
                  </div>
                  <p className="text-[11px] font-mono text-[var(--color-text-secondary)]">
                    {session.browser} • {session.ip} • {session.location}
                  </p>
                  <p className="text-[10px] font-mono text-[var(--color-text-muted)]">
                    Last active: {session.lastActive}
                  </p>
                </div>
              </div>

              {!session.isCurrent && (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    playToggleSound();
                    revokeSession(session.id);
                  }}
                  className="text-rose-400 hover:text-rose-300 hover:bg-rose-500/10 border-rose-500/30 shrink-0 gap-1.5"
                >
                  <LogOut className="w-3.5 h-3.5" />
                  <span>Revoke Access</span>
                </Button>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
