import {
  Wallet,
  Building2,
  CreditCard,
  PiggyBank,
  TrendingUp,
  Coins,
  FolderPlus,
  Banknote,
  Target,
  Home,
  Utensils,
  ShoppingCart,
  Car,
  Zap,
  Film,
  ShoppingBag,
  HeartPulse,
  Tv,
  Briefcase,
  Laptop,
  Gift,
  ArrowLeftRight,
  MoreHorizontal,
  PieChart,
  type LucideIcon,
} from 'lucide-react';

const FINANCE_ICON_MAP: Record<string, LucideIcon> = {
  Wallet,
  Building2,
  CreditCard,
  PiggyBank,
  TrendingUp,
  Coins,
  FolderPlus,
  Banknote,
  Target,
  Home,
  Utensils,
  ShoppingCart,
  Car,
  Zap,
  Film,
  ShoppingBag,
  HeartPulse,
  Tv,
  Briefcase,
  Laptop,
  Gift,
  ArrowLeftRight,
  MoreHorizontal,
  PieChart,
};

export function getFinanceIcon(name?: string, fallback: LucideIcon = Wallet): LucideIcon {
  if (!name) return fallback;
  return FINANCE_ICON_MAP[name] || fallback;
}
