/**
 * @file financeConstants.ts
 * @description Standard financial categories, payment methods, account metadata, and initial seed dataset.
 * @module Features/Finance/Constants
 */

import { Account, Transaction, Budget, Bill, SavingsGoal } from '../types/finance.types';

export const FINANCE_CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
];

export const TRANSACTION_CATEGORIES = [
  { id: 'housing', name: 'Housing & Rent', color: '#6366F1', icon: 'Home', type: 'expense' },
  { id: 'food', name: 'Food & Dining', color: '#F59E0B', icon: 'Utensils', type: 'expense' },
  { id: 'groceries', name: 'Groceries', color: '#10B981', icon: 'ShoppingCart', type: 'expense' },
  { id: 'transportation', name: 'Transportation', color: '#3B82F6', icon: 'Car', type: 'expense' },
  { id: 'utilities', name: 'Utilities & Bills', color: '#EC4899', icon: 'Zap', type: 'expense' },
  { id: 'entertainment', name: 'Entertainment & Leisure', color: '#8B5CF6', icon: 'Film', type: 'expense' },
  { id: 'shopping', name: 'Shopping & Gear', color: '#14B8A6', icon: 'ShoppingBag', type: 'expense' },
  { id: 'healthcare', name: 'Health & Wellness', color: '#EF4444', icon: 'HeartPulse', type: 'expense' },
  { id: 'subscriptions', name: 'Subscriptions & SaaS', color: '#06B6D4', icon: 'Tv', type: 'expense' },
  { id: 'investments', name: 'Investments & Savings', color: '#10B981', icon: 'TrendingUp', type: 'expense' },
  { id: 'salary', name: 'Salary & Income', color: '#22C55E', icon: 'Briefcase', type: 'income' },
  { id: 'freelance', name: 'Freelance & Side Business', color: '#A855F7', icon: 'Laptop', type: 'income' },
  { id: 'dividends', name: 'Dividends & Returns', color: '#3B82F6', icon: 'Coins', type: 'income' },
  { id: 'gifts', name: 'Gifts & Refunds', color: '#F43F5E', icon: 'Gift', type: 'income' },
  { id: 'transfer', name: 'Internal Transfer', color: '#64748B', icon: 'ArrowLeftRight', type: 'transfer' },
  { id: 'custom', name: 'Miscellaneous', color: '#94A3B8', icon: 'MoreHorizontal', type: 'expense' },
];

export const PAYMENT_METHODS = [
  'Bank Transfer',
  'Credit Card',
  'Debit Card',
  'Cash',
  'Apple Pay / Google Pay',
  'Crypto Wallet',
  'Check',
];

export const ACCOUNT_TYPE_CONFIG: Record<string, { label: string; defaultColor: string; defaultIcon: string }> = {
  cash: { label: 'Cash & Wallet', defaultColor: '#10B981', defaultIcon: 'Banknote' },
  bank: { label: 'Checking Account', defaultColor: '#3B82F6', defaultIcon: 'Building2' },
  credit_card: { label: 'Credit Card', defaultColor: '#EF4444', defaultIcon: 'CreditCard' },
  savings: { label: 'High-Yield Savings', defaultColor: '#8B5CF6', defaultIcon: 'PiggyBank' },
  investment: { label: 'Investment & Brokerage', defaultColor: '#6366F1', defaultIcon: 'TrendingUp' },
  digital_wallet: { label: 'Digital Wallet', defaultColor: '#F59E0B', defaultIcon: 'Wallet' },
  crypto: { label: 'Crypto Assets', defaultColor: '#EC4899', defaultIcon: 'Coins' },
  custom: { label: 'Custom Account', defaultColor: '#64748B', defaultIcon: 'FolderPlus' },
};

// --- INITIAL SEED ACCOUNTS ---
export const SEED_ACCOUNTS: Account[] = [
  {
    id: 'acc_chase_main',
    userId: 'default_user',
    name: 'Chase Premier Checking',
    type: 'bank',
    balance: 14850.4,
    currency: 'USD',
    accountNumberLast4: '4892',
    institution: 'Chase Bank',
    color: '#3B82F6',
    icon: 'Building2',
    isHidden: false,
    isArchived: false,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z',
  },
  {
    id: 'acc_hysa_marcus',
    userId: 'default_user',
    name: 'Marcus HYSA 4.8%',
    type: 'savings',
    balance: 38200.0,
    currency: 'USD',
    accountNumberLast4: '1092',
    institution: 'Goldman Sachs',
    color: '#8B5CF6',
    icon: 'PiggyBank',
    interestRate: 4.8,
    isHidden: false,
    isArchived: false,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z',
  },
  {
    id: 'acc_fidelity_roth',
    userId: 'default_user',
    name: 'Fidelity Roth IRA & Index Funds',
    type: 'investment',
    balance: 62450.75,
    currency: 'USD',
    accountNumberLast4: '7731',
    institution: 'Fidelity Investments',
    color: '#6366F1',
    icon: 'TrendingUp',
    isHidden: false,
    isArchived: false,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z',
  },
  {
    id: 'acc_sapphire_reserve',
    userId: 'default_user',
    name: 'Chase Sapphire Reserve',
    type: 'credit_card',
    balance: 1420.5,
    currency: 'USD',
    accountNumberLast4: '9012',
    institution: 'Chase Bank',
    color: '#EF4444',
    icon: 'CreditCard',
    creditLimit: 25000,
    interestRate: 19.99,
    isHidden: false,
    isArchived: false,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z',
  },
  {
    id: 'acc_cash_wallet',
    userId: 'default_user',
    name: 'Physical Cash Wallet',
    type: 'cash',
    balance: 450.0,
    currency: 'USD',
    institution: 'Personal Cash',
    color: '#10B981',
    icon: 'Banknote',
    isHidden: false,
    isArchived: false,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z',
  },
];

// --- INITIAL SEED TRANSACTIONS ---
export const SEED_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_sal_01',
    userId: 'default_user',
    amount: 7850.0,
    currency: 'USD',
    type: 'income',
    category: 'Salary & Income',
    subcategory: 'Tech Corp Direct Deposit',
    accountId: 'acc_chase_main',
    date: '2026-07-31',
    time: '09:00',
    merchant: 'Acme Tech Corp',
    paymentMethod: 'Bank Transfer',
    notes: 'Bi-weekly tech engineering payroll payout',
    tags: ['Payroll', 'Income', 'Salary'],
    status: 'completed',
    isFavorite: true,
    createdAt: '2026-07-31T09:00:00.000Z',
    updatedAt: '2026-07-31T09:00:00.000Z',
  },
  {
    id: 'tx_rent_01',
    userId: 'default_user',
    amount: 2850.0,
    currency: 'USD',
    type: 'expense',
    category: 'Housing & Rent',
    subcategory: 'Apartment Lease',
    accountId: 'acc_chase_main',
    date: '2026-08-01',
    time: '10:15',
    merchant: 'Avalon Luxury Apartments',
    paymentMethod: 'Bank Transfer',
    notes: 'August Rent Payment',
    tags: ['Housing', 'Fixed'],
    status: 'completed',
    isFavorite: false,
    isRecurring: true,
    recurrenceFrequency: 'monthly',
    createdAt: '2026-08-01T10:15:00.000Z',
    updatedAt: '2026-08-01T10:15:00.000Z',
  },
  {
    id: 'tx_groc_01',
    userId: 'default_user',
    amount: 184.25,
    currency: 'USD',
    type: 'expense',
    category: 'Groceries',
    subcategory: 'Organic Produce',
    accountId: 'acc_sapphire_reserve',
    date: '2026-07-30',
    time: '17:45',
    merchant: 'Whole Foods Market',
    paymentMethod: 'Credit Card',
    notes: 'Weekly fresh produce, salmon & artisanal bread',
    tags: ['Food', 'Groceries'],
    status: 'completed',
    isFavorite: false,
    createdAt: '2026-07-30T17:45:00.000Z',
    updatedAt: '2026-07-30T17:45:00.000Z',
  },
  {
    id: 'tx_sub_cloud',
    userId: 'default_user',
    amount: 29.99,
    currency: 'USD',
    type: 'expense',
    category: 'Subscriptions & SaaS',
    subcategory: 'Developer Infrastructure',
    accountId: 'acc_sapphire_reserve',
    date: '2026-07-28',
    time: '12:00',
    merchant: 'Vite / Cloud Platform',
    paymentMethod: 'Credit Card',
    notes: 'Monthly AI Studio cloud tier',
    tags: ['SaaS', 'Work'],
    status: 'completed',
    isFavorite: false,
    createdAt: '2026-07-28T12:00:00.000Z',
    updatedAt: '2026-07-28T12:00:00.000Z',
  },
  {
    id: 'tx_invest_roth',
    userId: 'default_user',
    amount: 500.0,
    currency: 'USD',
    type: 'transfer',
    category: 'Internal Transfer',
    subcategory: 'Roth IRA Contribution',
    accountId: 'acc_chase_main',
    targetAccountId: 'acc_fidelity_roth',
    date: '2026-07-25',
    time: '14:30',
    merchant: 'Fidelity Direct Auto-Invest',
    paymentMethod: 'Bank Transfer',
    notes: 'Monthly S&P 500 Vanguard Index contribution',
    tags: ['Investing', 'Retirement'],
    status: 'completed',
    isFavorite: true,
    isRecurring: true,
    recurrenceFrequency: 'monthly',
    createdAt: '2026-07-25T14:30:00.000Z',
    updatedAt: '2026-07-25T14:30:00.000Z',
  },
  {
    id: 'tx_dining_01',
    userId: 'default_user',
    amount: 145.0,
    currency: 'USD',
    type: 'expense',
    category: 'Food & Dining',
    subcategory: 'Omakase Sushi',
    accountId: 'acc_sapphire_reserve',
    date: '2026-07-24',
    time: '20:30',
    merchant: 'Sushi Taro Downtown',
    paymentMethod: 'Credit Card',
    notes: 'Dinner with product team',
    tags: ['Dining', 'Social'],
    status: 'completed',
    createdAt: '2026-07-24T20:30:00.000Z',
    updatedAt: '2026-07-24T20:30:00.000Z',
  },
  {
    id: 'tx_free_client',
    userId: 'default_user',
    amount: 2200.0,
    currency: 'USD',
    type: 'income',
    category: 'Freelance & Side Business',
    subcategory: 'UI Architecture Design',
    accountId: 'acc_chase_main',
    date: '2026-07-20',
    time: '11:00',
    merchant: 'Linear Design Studio',
    paymentMethod: 'Bank Transfer',
    notes: 'Q3 UI System Consulting milestone 2',
    tags: ['Freelance', 'Design'],
    status: 'completed',
    createdAt: '2026-07-20T11:00:00.000Z',
    updatedAt: '2026-07-20T11:00:00.000Z',
  },
];

// --- INITIAL SEED BUDGETS ---
export const SEED_BUDGETS: Budget[] = [
  {
    id: 'bgt_housing',
    userId: 'default_user',
    name: 'Housing & Rent',
    category: 'Housing & Rent',
    amountLimit: 3000.0,
    period: 'monthly',
    periodDate: '2026-08',
    alertThresholdPercent: 90,
    color: '#6366F1',
    icon: 'Home',
    isArchived: false,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'bgt_food',
    userId: 'default_user',
    name: 'Food & Dining out',
    category: 'Food & Dining',
    amountLimit: 600.0,
    period: 'monthly',
    periodDate: '2026-08',
    alertThresholdPercent: 80,
    color: '#F59E0B',
    icon: 'Utensils',
    isArchived: false,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'bgt_groceries',
    userId: 'default_user',
    name: 'Groceries & Essentials',
    category: 'Groceries',
    amountLimit: 750.0,
    period: 'monthly',
    periodDate: '2026-08',
    alertThresholdPercent: 85,
    color: '#10B981',
    icon: 'ShoppingCart',
    isArchived: false,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'bgt_entertainment',
    userId: 'default_user',
    name: 'Entertainment & Hobbies',
    category: 'Entertainment & Leisure',
    amountLimit: 400.0,
    period: 'monthly',
    periodDate: '2026-08',
    alertThresholdPercent: 75,
    color: '#8B5CF6',
    icon: 'Film',
    isArchived: false,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'bgt_shopping',
    userId: 'default_user',
    name: 'Shopping & Gear',
    category: 'Shopping & Gear',
    amountLimit: 500.0,
    period: 'monthly',
    periodDate: '2026-08',
    alertThresholdPercent: 80,
    color: '#14B8A6',
    icon: 'ShoppingBag',
    isArchived: false,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
];

// --- INITIAL SEED BILLS ---
export const SEED_BILLS: Bill[] = [
  {
    id: 'bill_rent',
    userId: 'default_user',
    title: 'Apartment Rent',
    amount: 2850.0,
    currency: 'USD',
    category: 'Housing & Rent',
    accountId: 'acc_chase_main',
    payee: 'Avalon Apartments',
    dueDate: '2026-08-01',
    recurrence: 'monthly',
    status: 'paid',
    autoPay: true,
    reminderDays: 3,
    lastPaidDate: '2026-08-01',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'bill_wifi',
    userId: 'default_user',
    title: 'Gigabit Fiber Internet',
    amount: 89.99,
    currency: 'USD',
    category: 'Utilities & Bills',
    accountId: 'acc_sapphire_reserve',
    payee: 'Sonic Fiber',
    dueDate: '2026-08-10',
    recurrence: 'monthly',
    status: 'unpaid',
    autoPay: true,
    reminderDays: 2,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'bill_gym',
    userId: 'default_user',
    title: 'Equinox All-Access Club',
    amount: 280.0,
    currency: 'USD',
    category: 'Health & Wellness',
    accountId: 'acc_sapphire_reserve',
    payee: 'Equinox Fitness',
    dueDate: '2026-08-15',
    recurrence: 'monthly',
    status: 'unpaid',
    autoPay: false,
    reminderDays: 5,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'bill_electric',
    userId: 'default_user',
    title: 'PG&E Electric Utility',
    amount: 142.5,
    currency: 'USD',
    category: 'Utilities & Bills',
    accountId: 'acc_chase_main',
    payee: 'Pacific Gas & Electric',
    dueDate: '2026-08-18',
    recurrence: 'monthly',
    status: 'unpaid',
    autoPay: true,
    reminderDays: 3,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
];

// --- INITIAL SEED SAVINGS GOALS ---
export const SEED_SAVINGS_GOALS: SavingsGoal[] = [
  {
    id: 'goal_efund',
    userId: 'default_user',
    name: '6-Month Emergency Cushion',
    targetAmount: 30000.0,
    currentAmount: 24500.0,
    currency: 'USD',
    category: 'Emergency Fund',
    targetDate: '2026-12-31',
    monthlyContribution: 1000.0,
    color: '#10B981',
    icon: 'ShieldCheck',
    accountId: 'acc_hysa_marcus',
    isCompleted: false,
    isArchived: false,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'goal_japan',
    userId: 'default_user',
    name: 'Tokyo & Kyoto Spring Trip',
    targetAmount: 6500.0,
    currentAmount: 4800.0,
    currency: 'USD',
    category: 'Vacation Fund',
    targetDate: '2027-04-01',
    monthlyContribution: 500.0,
    color: '#EC4899',
    icon: 'Plane',
    accountId: 'acc_hysa_marcus',
    isCompleted: false,
    isArchived: false,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'goal_tesla',
    userId: 'default_user',
    name: 'EV Down Payment',
    targetAmount: 15000.0,
    currentAmount: 8900.0,
    currency: 'USD',
    category: 'Custom Savings',
    targetDate: '2027-01-15',
    monthlyContribution: 800.0,
    color: '#3B82F6',
    icon: 'Car',
    accountId: 'acc_hysa_marcus',
    isCompleted: false,
    isArchived: false,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
];
